language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
services:
  - mongodb
before_script:
  - cp config/mongoid.yml.sample config/mongoid.yml
#  - RAILS_ENV=test bundle exec rake db:create db:migrate
install: bundle install --path vendor/bundle --binstubs vendor/bundle/bin --jobs=3 --retry=3
script: 
  - RAILS_ENV=test bundle exec rake test
cache:
  directories:
    - vendor/bundle


