language: ruby

rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - cp config/database.yml.sample config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
install: bundle install --path vendor/bundle --binstubs vendor/bundle/bin --jobs=3 --retry=3
script: 
  - RAILS_ENV=test bundle exec rake test
cache:
  directories:
    - vendor/bundle


