development:
  # Configure available database sessions. (required)
  clients:
    # Defines the default session. (required)
    default:
      database: randomImage
      hosts:
        - 52.11.154.135:27017
      username: 'random_admin'
      password: 'random12!@'
      options:
        user: "random_admin"
        password: "random12!@"
  # Configure Mongoid specific options. (optional)
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serializaion. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Protect id and type from mass assignment. (default: true)
    # protect_sensitive_fields: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  clients:
    default:
      database: randomImage
      hosts:
        - localhost:27017
      username: 'admin'
      password: 'teset'
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  clients:
    # Define the default session.
    default:
      # A session can have any number of hosts. Usually 1 for a single
      # server setup, and at least 3 for a replica set. Hosts must be
      # an array of host:port pairs. This session is single server.
      database: randomImage
      hosts:
        - <%= ENV['MONGODB_URI'] %>
      username: <%= ENV['MONGO_ID'] %>
      password: <%= ENV['MONGO_PWD'] %>
      options:
        user: <%= ENV['MONGO_ID'] %>
        password: <%= ENV['MONGO_PWD'] %>
      # Define the default database name.
      # Since this database points at a session connected to MongoHQ, we must
      # provide the authentication details.
    # This defines a secondary session at a replica set.
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    # Note this can also be true if you want to preload everything, but this is
    # almost never necessary. Most of the time set this to false.
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true
